from app.models import db
from app.models import Game

def seed_games():
  game1 = Game(category_id=1, title='Red Dead Redemption 2', 
  img='https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg',
  description='America, 1899. The end of the wild west era has begun as lawmen hunt down the last remaining outlaw gangs. Those who will not surrender or succumb are killed. After a robbery goes badly wrong in the western town of Blackwater, Arthur Morgan and the Van der Linde gang are forced to flee. With federal agents and the best bounty hunters in the nation massing on their heels, the gang must rob, steal and fight their way across the rugged heartland of America in order to survive. As deepening internal divisions threaten to tear the gang apart, Arthur must make a choice between his own ideals and loyalty to the gang who raised him. From the creators of Grand Theft Auto V and Red Dead Redemption, Red Dead Redemption 2 is an epic tale of life in America at the dawn of the modern age.')
  game2 = Game(category_id=1, title='Grand Theft Auto V', 
  img='https://upload.wikimedia.org/wikipedia/en/a/a5/Grand_Theft_Auto_V.png',
  description='Rockstar Games went bigger, since their previous installment of the series. You get the complicated and realistic world-building from Liberty City of GTA4 in the setting of lively and diverse Los Santos, from an old fan favorite GTA San Andreas. 561 different vehicles (including every transport you can operate) and the amount is rising with every update. Simultaneous storytelling from three unique perspectives: Follow Michael, ex-criminal living his life of leisure away from the past, Franklin, a kid that seeks the better future, and Trevor, the exact past Michael is trying to run away from. GTA Online will provide a lot of additional challenge even for the experienced players, coming fresh from the story mode. Now you will have other players around that can help you just as likely as ruin your mission. Every GTA mechanic up to date can be experienced by players through the unique customizable character, and community content paired with the leveling system tends to keep everyone busy and engaged.')
  game3 = Game(category_id=1, title='Ashen', 
  img='https://upload.wikimedia.org/wikipedia/en/7/77/Ashen.jpg',
  description='Ashen is an action RPG about a wanderer in search of a place to call home. This is a world where nothing lasts, no matter how tightly you cling to it. Players may cross paths with one another, and choose to guide those they trust to their camp, encouraging them to rest at the fire and perhaps remain. When someone joins your settlement, they come with unique skills and crafting abilities to bolster your chances of survival. Together, you might just stand a chance.')
  game4 = Game(category_id=1, title='Dark Souls: Remastered', 
  img='https://upload.wikimedia.org/wikipedia/en/8/8d/Dark_Souls_Cover_Art.jpg',
  description='Then, there was fire. Re-experience the critically acclaimed, genre-defining game that started it all. Beautifully remastered, return to Lordran in stunning high-definition detail running at 60fps. Dark Souls Remastered includes the main game plus the Artorias of the Abyss DLC. Key features: • Deep and Dark Universe • Each End is a New Beginning • Gameplay Richness and Possibilities • Sense of Learning, Mastering and Accomplishment • The Way of the Multiplayer (up to 6 players with dedicated servers)')
  game5 = Game(category_id=1, title='Strange Brigade', 
  img='https://upload.wikimedia.org/wikipedia/en/5/5e/Strange_Brigade_cover_art.png',
  description='There are remote corners of the British Empire where the shadows linger at their deepest. The servants of The Crown know about these places and the supernatural beings that sometimes lurk there. Introducing the fearless and unflinching STRANGE BRIGADE! Embark on an exotic safari into DANGER where few dare go and fewer return! Encounter FANTASTIC and forgotten civilizations shrouded in MYSTERY! Uncover TREACHEROUS tombs and unfathomable EVIL, never-before-seen by any human now living! This pulse-pounding adventure will rivet you to your game controller! Don’t fail to play: STRANGE BRIGADE! FOUR FEARLESS ADVENTURERS! Explore the ancient world as one of four dashing explorers, each with their own special powers, weapons and tactics.')
  game6 = Game(category_id=1, title='State of Decay 2', 
  img='https://upload.wikimedia.org/wikipedia/en/9/9d/State_of_Decay_2_art.jpg',
  description='State of Decay 2 is an open-world zombie-themed survival game with RPG elements, the second installment in State of Decay series. Gameplay In State of Decay 2, you take a role of zombie-apocalypse survivor. After the tutorial, you can choose one of three maps to explore. The goal of the game is to clear the maps from Plague Hearts – sources of Blood Plague disease that makes zombies more aggressive and dangerous. The world is entirely free to explore. Throughout it, you come across survivor’s bases that you can upgrade with different facilities such as kitchens, gardens, workshops and many more. During the game you are also going to meet new survivors, that would join you and become playable. Each survivor has its progression system with numerous stats to upgrade and abilities to unlock. The death in the game is permanent for every survivor. The game offers many unique items and weapons, both ranged and melee, to fight zombies and hostile survivors. ')
  game7 = Game(category_id=1, title='Titan Quest', 
  img='https://upload.wikimedia.org/wikipedia/en/1/1c/Titan_Quest.jpg',
  description='The plot of the game is intimately connected with the mythology of Ancient Greece, Egypt and the East and tells about the campaign of the main hero against a trio of lesser Titans known as Telkines, massive creatures, who took advantage of depriving people of divine guardianship to give the Earth to the power of the Titans. In the gameplay, the primary focus is made on destroying numerous monsters and developing character characteristics and skills. The plot is directly divided into three acts, and the game world, respectively, into three broad areas: Ancient Greece, Ancient Egypt and the Ancient East, as well as the final location - Olympus. One of the features of the gameplay is the presence of many elements, borrowings and references to lands, characters, weapons and monsters from the ancient mythologies of the Greeks and Egyptians, and the plot bosses are the murderer of Hercules - Nessus, the huge scarab and demonic bull.')
  game8 = Game(category_id=1, title='Monster Hunter: World', 
  img='https://upload.wikimedia.org/wikipedia/en/1/1b/Monster_Hunter_World_cover_art.jpg',
  description='Monster Hunter: World is the fifth game in the Japanese franchise Monster Hunter, which is about hunting giant beasts. It is set in a medieval fantasy setting, on a continent known as the New World that is being colonized by the humans from the Old World. The plot revolves around a dragon migration called Elder Crossing. Your protagonist is a hunter, whose name and appearance can be customized. You traveled from the Old World to study and hunt the dragons and other local monsters. The hunter, accompanied by an assistant, starts at the city of Astera, from where they can freely wander the open world. There are six regions in the New World, each with its own base camp. The camps are where you have to thoroughly prepare before every expedition, gathering equipment and provision. Before you can fight monsters, they need to be tracked down using Scout flies and studied to discover their habits, strengths, and weaknesses. ')
  game9 = Game(category_id=1, title='ToeJam & Earl: Back in the Groove', 
  img='https://upload.wikimedia.org/wikipedia/en/d/d4/ToeJam_%26_Earl_BitG_pre-release_Steam_header.jpg',
  description="ToeJam and Earl: Back in the Groove is an all-new adventure developed by the co-creator of the OG ToeJam and Earl games, which famously infused hip-hop stylings with rogue-like game play. Crash land on Earth and protect yourself with funky power-ups against dangerous Earthlings on an adventure to find all the lost pieces of the Rapmaster Rocketship. Play with up to three of your friends online or couch co-op and discover all the secret locations and powerful tools. ToeJam and Earl probably shouldn't have taken the Rapmaster on an intergalactic joyride, but at least they'll find all the pieces of it before Lamont notices that it's missing ... right? Right.")
  game10 = Game(category_id=1, title="Marvel's Avengers", 
  img='https://upload.wikimedia.org/wikipedia/en/c/c0/Avengers_2020_cover_art.png',
  description='Marvel’s Avengers is an epic, third-person, action-adventure game that combines an original, cinematic story with single-player and co-operative gameplay. Assemble into a team of up to four players online, master extraordinary abilities, customize a growing roster of Heroes, and defend the Earth from escalating threats. The game features iconic Heroes as you’ve never seen them before, notable villains, recognizable locations, and awesome powers set in an original Avengers story. Unlock powerful skills, heroic abilities, and unique gear for each of Earth’s Mightiest Heroes to suit your playstyle. Up to four players assemble online to defend the Earth from escalating threats that only the Avengers can overcome.')
  game11 = Game(category_id=1, title="Anthem", 
  img="https://upload.wikimedia.org/wikipedia/en/4/49/Cover_Art_of_Anthem.jpg",
  description='Anthem is a multiplayer-oriented game where teams of players share a common futuristic world while fighting enemies with the use of their armored power suits.')
  game12 = Game(category_id=1, title='Doom(2016)', 
  img='https://upload.wikimedia.org/wikipedia/en/2/28/Doom_Cover.jpg',
  description='Return of the classic FPS, Doom (2016) acts as a reboot of the series and brings back the Doomslayer, protagonist of the original Doom games. In order to solve the energy crisis, humanity learned to harvest the energy from Hell, and when something went wrong and demon invasion has started, it’s up to the player to control the Doomslayer and destroy the evil. Doom is a fast-paced game that restores the concept of instant health packs and leaving the player against armies of Hell with no cover, no health regeneration or help from anyone. ')
  game13 = Game(category_id=2, title='The Witcher 3: Wild Hunt', 
  img='https://upload.wikimedia.org/wikipedia/en/0/0c/Witcher_3_cover_art.jpg',
  description='The third game in a series, it holds nothing back from the player. Open world adventures of the renowned monster slayer Geralt of Rivia are now even on a larger scale. Following the source material more accurately, this time Geralt is trying to find the child of the prophecy, Ciri while making a quick coin from various contracts on the side. Great attention to the world building above all creates an immersive story, where your decisions will shape the world around you. CD Project Red are infamous for the amount of work they put into their games, and it shows, because aside from classic third-person action RPG base game they provided 2 massive DLCs with unique questlines and 16 smaller DLCs, containing extra quests and items. Players praise the game for its atmosphere and a wide open world that finds the balance between fantasy elements and realistic and believable mechanics, and the game deserved numerous awards for every aspect of the game, from music to direction.')
  game14 = Game(category_id=2, title='Far Cry: New Dawn', 
  img='https://upload.wikimedia.org/wikipedia/en/9/96/FC_New_Dawn_cover_art.jpg',
  description="Dive into a transformed vibrant post-apocalyptic Hope County, Montana, 17 years after a global nuclear catastrophe. Join fellow survivors and lead the fight against the dangerous new threat the Highwaymen, and their ruthless leaders The Twins, as they seek to take over the last remaining resources. FIGHT FOR SURVIVAL IN A POST-APOCALYPTIC WORLD • Take up arms on your own or with a friend in two player co-op in an unpredictable and transformed world COLLIDE AGAINST TWO ALL NEW VILLAINS • Recruit an eclectic cast of Guns and Fangs for Hire and form alliances to fight by your side against the Highwaymen's unruly leaders The Twins BUILD UP YOUR HOMEBASE AND THE SURVIVORS • Recruit Specialists to upgrade your homebase, who will help unlock all new features including crafting weapons, gear and more BATTLE FOR RESOURCES IN HOPE COUNTY AND BEYOND • Engage the Highwaymen in Turf Wars and venture on Expeditions to memorable locations across the USA")
  game15 = Game(category_id=2, title="No Man's Sky", 
  img='https://upload.wikimedia.org/wikipedia/en/6/67/No_Man%27s_Sky.jpg',
  description="No Man's Sky is a space action-adventure survival game developed by Hello Games. The overall visual style of the game is inspired by various science fiction books. Demoscene also served as a source of inspiration for the developers. The main feature that the game revolves around is the procedural generation. Each planet you visit is generated from scratch. The information about the planets and their inhabitants is dynamically updated so every player can discover a new species or planet and give it a name. No Man's Sky gameplay implies the exploration of space and planets some of which are inhabited with extra-terrestrial life, gathering resources, space battles, maintaining and upgrading the player's ship and completing bounty hunting missions. The main objective is to reach the center of the galaxy. On release, it was stated that the game is in fact multiplayer, but the size of its world is so big that the probability of meeting another player is extremely small. It turned out that it is impossible to meet any other player due to the extremely limited multiplayer aspect. As of 2018, Hello Games released the fourth major update which included the full multiplayer experience.")
  game16 = Game(category_id=2, title='A Way Out', 
  img='https://upload.wikimedia.org/wikipedia/en/8/83/A_Way_Out_Logo.jpg',
  description='This action-adventure game released under the auspices of EA Originals Electronic Arts initiative. The game can not be played alone: ​​there is simply no singleplayer. The available options are either to play the game on one device using split-screen or using the online multiplayer. You do not need to buy two games to play with somebody: when buying a friend, you can give the code for downloading a full version of the game, which, however, will be active only if you pass it together. The story tells of two prisoners who were together in one prison in the US at the beginning of the 70s. To avoid the dangers of prison, they decide to flee. A Way Out is a third-person adventure game in which the story is told simultaneously for two characters. Since they develop asynchronously, there are often situations where one of the players loses the control over the character because of the story cutscene, and the other can safely move around the prison. Roles are not fixed and can change during the playthrough.')
  game17 = Game(category_id=2, title='Crackdown 3', 
  img='https://upload.wikimedia.org/wikipedia/en/0/02/Crackdown_3_cover.jpg',
  description="Crackdown 3 is the sequel to 2010s Crackdown 2 and the third game in its series. Crackdown 3 uses Microsoft Azure cloud computing service to improve the game's performance.")
  game18 = Game(category_id=2, title='Portal', 
  img='https://upload.wikimedia.org/wikipedia/en/9/9f/Portal_standalonebox.jpg',
  description='Every single time you click your mouse while holding a gun, you expect bullets to fly and enemies to fall. But here you will try out the FPS game filled with environmental puzzles and engaging story. Silent template for your adventures, Chell, wakes up in a testing facility. She’s a subject of experiments on instant travel device, supervised by snarky and hostile GLaDOS. Players will have to complete the tests, room by room, expecting either reward, freedom or more tests. By using the gun, that shoots portals (Portal-Gun™), players will move blocks, travel great distance quickly and learn about your current situation, which is unraveled through environmental storytelling. What you will be told might be different from what you will see. White environments will guide the player’s portal placement, forcing them to pay attention to the surroundings. Portal creates tension, allowing either solving puzzles at your own leisure or moving quickly, due to the time limit or threats.')
  game19 = Game(category_id=3, title='Limbo', 
  img='https://upload.wikimedia.org/wikipedia/en/c/cc/Limbo_Box_Art.jpg',
  description='This popular 2D puzzle-platformer creates the atmosphere of isolation, where the player alone can guide the nameless protagonist to his destination. Hostile environments and one-hit deaths may seem difficult, but the game implements a fair amount of checkpoints. The monochrome color palette showcases cartoony proportions of every living thing while making lack of details threatening. Limbo shows you exactly what you encounter, but never how it looks. Limbo uses the atmosphere and sound design of the horror genre while avoiding tropes of the modern horror games. The overarching theme and unique style compensated for the rather short game with an abrupt ending, making Limbo one of the most impactful games for the genre. The simple controls and easy-to-pick-up mechanics help to make a clear distinction, which part of the stage players can interact with, and which part can lead to the quick death. Even though the game is in black and white, this separation is intuitive and natural, so the player would know exactly where to go or what to do.')
  game20 = Game(category_id=3, title='Human: Fall Flat', 
  img='https://thumbnails.pcgamingwiki.com/1/1e/Human_Fall_Flat_cover.jpg/300px-Human_Fall_Flat_cover.jpg',
  description='Human: Fall Flat is a low-poly adventure game with platforming elements and physics-based puzzles. You play as Bob, a fully customizable character that travels from one dream to another. Bob has neither no background nor superpowers. His abilities don’t differ from yours: he can grab things, climb ledges and so on. Every level consists of multiple puzzles that can be solved in different ways. You can push and pull carts, break walls and interact with everything else comparable to your own size. The game heavily focuses on physics. Puzzles’ solutions are intuitive and make you act like in real life. In their core levels are quite linear: you need to reach the door at another side of the location to get into the next dream. While at the first levels you need to find exits from tiny rooms, the further you go, the larger locations become. There is a lot of content in the game in general, and it clearly references the sandbox genre where you can do almost everything you want.')
  game21 = Game(category_id=3, title='Trine 2: Complete Story', 
  img='https://2.bp.blogspot.com/-MFZC7gZfjxw/XG2FHO7GYWI/AAAAAAAAO-M/mDKWy3SXSU4NneVVxgaYtne8dfw6RaO8wCLcBGAs/s640/trine-2-complete-story-nintendo-switch.png',
  description='Trine II takes a few years after the first game. Successfully saving the kingdom, Amadeus seeks the fireball spells. Yet he is summoned to save the homeland with his friends - Zoya and Pontious. Goblins have taken over the land as they are trying to find the mysterious "Witch" deep in the forest. Although having more than one playable character, Trine successfully uses all three of them. Amadeus as the mage is able to move objects or create boxes and planks to help overcome some obstacles. Zoya is very agile so she can hook and grapple on some surfaces, or shoot different targets. Pontious is the strongest character in combat, and he can destroy walls in his path or deflect things with his shield. Having this three different characters, it is necessary to use all three of them to solve puzzles and beat the level. Not only you can play alone, but the game supports three players cooperative to make progress even more atmospheric. Beautiful design, music and a narrator makes Trine a great story, that feels inspired by J.R.R. Tolkien himself.')
  game22 = Game(category_id=3, title='Broken Age', 
  img='https://upload.wikimedia.org/wikipedia/en/3/3f/Broken_Age_cover_art.jpg',
  description='Broken Age is a classic point-and-click adventure game, which tells a story of two completely different teenagers seeking to change their life pace. The action takes place in an imaginary universe shown in a 2.5D perspective. The gameplay is divided into two main storylines, so players are able to assume the roles of both Vella Tartine and Shay Volta. The game allows switching characters at any time. Firstly, events move players to Sugar Bunting town occupied by fictional monsters called Mogs, which demand a sacrifice of young girls every 14 years. Once the protagonist Vella finds herself chosen to be the sacrificed maiden. As she tries to stay alive, she realizes that the only way out is to fight the monster and to liberate her hometown. The second story tells about Shay, a lone boy imprisoned in a spaceship between two AI systems. The boy seeks independence and starts to explore the entire ship then moving to the whole war-torn galaxy. Both storylines are not expected to connect somehow, but in the course of completion game levels, players start to notice similar slight details.')
  game23 = Game(category_id=3, title='Unravel', 
  img='https://upload.wikimedia.org/wikipedia/en/6/6a/Unravel_cover_art.jpg',
  description="The player controls Yarni, a man of yarn. Yarni arises in the human house, from the tangle of yarn used for knitting by the inhabitants of this house. Yarni moves around the house, goes into the yard, examines the neighborhood. It is small and therefore a mug, flower bed or children's bicycle are obstacles in its way. But the yarn that Yarni is made of is subject to him, he can catch on to the object, pull himself up and climb up, swing and jump, maybe even pull yarn and walk along it like a tightrope walker. The variety of these techniques is large enough, tips help to use them. You can interact with all objects, sometimes there are creatures that can block the path - for example, insects. Yarn can not be unrolled indefinitely, it is necessary to monitor its consumption. Sometimes you can return the unwound yarn back to the body, sometimes you can increase the amount of yarn, finding a new piece. The most valuable thing Yarni finds is memories. Memories of a family of people, from which he comes himself. Memories are painted with different emotions, a sufficient number of collected memories opens the entrance to the following levels.")
  game24 = Game(category_id=3, title='Trine 4: The Nightmare Prince', 
  img='https://static-cdn.jtvnw.net/ttv-boxart/Trine%204%3A%20The%20Nightmare%20Prince.jpg',
  description='The Trine series returns to the magic of 2.5D with Trine 4: The Nightmare Prince! The three heroes of the best-selling adventure series are back, sent on a quest to retrieve the troubled young Prince Selius. Amadeus the Wizard, Pontius the Knight, and Zoya the Thief are joined together once again on a thrilling quest through fantastical fairytale landscapes teeming with danger. Trine 4 reaches new heights in the series, bringing the most complete 2.5D gameplay experience ever to fans and new players alike.')
  game25 = Game(category_id=4, title='Rocket League', 
  img='https://upload.wikimedia.org/wikipedia/commons/e/e0/Rocket_League_coverart.jpg',
  description='Highly competitive soccer game with rocket-cars is the most comprehensive way to describe this game. Technically a sequel to Psyonix’ previous game - Supersonic Acrobatic Rocket-Powered Battle-Cars; Rocket League successfully became a standalone sensation, that can be enjoyed by anyone. Easy to learn, hard to master game mechanics are perfect for the tight controls. Players are invited to maneuver the different fields within several game modes, from arcade to ranked game either 1v1, or in 2v2 and 3v3 teams. Using boosters will not only speed up the car but will allow the car to propel itself into the air. Rocket League provides several levels of customization, where not only the color of your car can be adjusted, but the colors and form of the booster flame, different hats, and little flags. Or players can pick a completely different car. Collaboration with different franchises brought not only original transport but some famous cars, including Batmobile or Delorian from Back to the Future.')
  game26 = Game(category_id=4, title='SpeedRunners', 
  img='https://upload.wikimedia.org/wikipedia/en/9/95/SpeedRunners.jpg',
  description='In a city filled with superheroes, getting to crimes becomes a competition on its own. Fortunately there are enough rockets, bombs, grappling hooks, spikes, and other goodies lying around -- to make the competition fun and fast. Welcome to SpeedRunners. SpeedRunners is a 4 player competitive platformer with grappling hooks, power-ups, and interactive environments. Run, jump, swing around, fire rockets, grapple onto people to knock them off screen.Key Features4 Player Competitive Platforming! Keep up with the fastest player in-game, or fall offscreen and get eliminated! Use weapons like missiles, mines and grappling hooks to screw over your friends, and make new enemies! Local and online multiplayer! Can you have 2 players on a couch against 2 other players on the internet? Yes of course! Bots enabled - play on your own with several AI opponents. Or put them into matches with other people!')
  game27 = Game(category_id=4, title='Forza Horizon 4', 
  img='https://upload.wikimedia.org/wikipedia/en/8/87/Forza_Horizon_4_cover.jpg',
  description='Forza Horizon 4 is the eleventh game in the Forza franchise of racing games and the fourth in the Horizon subseries. Forza Horizon 4 takes place in a shared open world that is loosely based on the United Kingdom. Up to 72 players can share a server at which they participate in races together. They can also purchase in-game homes, which allow the players to unlock faster cars and driver perks. The drivers are customizable up to their clothing and emotions.')
  game28 = Game(category_id=4, title='GRID 2', 
  img='https://upload.wikimedia.org/wikipedia/en/a/a1/Grid_2_cover.jpg',
  description='GRID 2 is a racing game, the sequel to Race Driver: GRID. In the centre of the "story" GRID 2 is a racing championship, which we gradually promote around the world. Money is not needed, the main thing is to conquer the audience. The race will be held in such places as Paris, Hong Kong, Chicago, Dubai, etc. All the tracks, drivers, teams, cars and sponsors in the game are real. Compared to GRID (the first part of the series), there are more modes. There were races on the so-called "Checkpoint", endurance race and other several options. And the significant thing now that there is no driving on the rails, sudden acceleration of rivals and unpunished wiping of bumpers (also, damage to the machine is not displayed on the screen, it is necessary to focus on its behaviour and the replica of racing engineer). The main feature of GRID is time rewinding. The number of rewinds is limited, but with this, you can save yourself from a fatal outcome.')
  game29 = Game(category_id=4, title='Need For Speed: Hot Pursuit', 
  img='https://upload.wikimedia.org/wikipedia/en/8/85/Need_for_Speed_Hot_Pursuit_2010.jpg',
  description="Need For Speed: Hot Pursuit is an arcade racing game, where you complete missions switching between a police officer and a racer. While the goal is the same - to reach the finish first, the game allows trying another side of races as you need to stop a lawbreaker in the police part of the game. Unlike typical racing titles, Hot Pursuit follows the principle that 'all is fair.' That's why both sides have special tools to stop the opponent. You can throw spikes on the road or use turbo acceleration to break away from the pursuit. Police can block the road and summon a helicopter for help from above.  Additionally, Hot Pursuit features a new Autolog social system. With it, you can compete with your friends and see the statistics on every race. The system compares your results with your friends' ones and notifies you every time your record is beaten.")
  game30 = Game(category_id=5, title='Divinity: Original Sin 2', 
  img='https://upload.wikimedia.org/wikipedia/en/4/48/Divinity_Original_Sin_2_cover_art.jpg',
  description='The Divine is dead. The Void approaches. And the powers latent within you are soon to awaken. The battle for Divinity has begun. Choose wisely and trust sparingly; darkness lurks within every heart. Who will you be? A flesh-eating elf; an imperial lizard; an undead risen from the grave? Choose your race and origin story - or create your own! Discover how the world reacts differently to who - and what - you are.It’s time for a new Divinity! Gather your party and develop relationships with your companions. Blast your opponents in deep tactical turn-based combat. Use the environment as a weapon, use height to your advantage, and manipulate the elements.Ascend as the god that Rivellon so desperately needs. Explore the vast and layered world of Rivellon alone or with up to 4 players in drop-in/drop-out co-operative play. Go anywhere, kill anyone, and explore endless ways to interact with the world. Continue to play in the brand-new PvP and Game Master modes. Choose your race and origin. or create your own as a Human, Lizard, Elf, Dwarf, or Undead. The world reacts to who you are, and what you’ve done. Every choice will have a consequence. Unlimited freedom to explore and experiment. Go anywhere, talk to anyone, and interact with everything! Every NPC can be killed, and every animal spoken to! Even ghosts hold a few secrets or two… The next generation of turn-based combat. Revamped action point system, AI 2.0., new elemental combos, over 200 skills, height advantage… and much, much more. Up to 4 player online and split-screen multiplayer.')
  game31 = Game(category_id=5, title='The Elder Scrolls V: Skyrim', 
  img='https://upload.wikimedia.org/wikipedia/en/1/15/The_Elder_Scrolls_V_Skyrim_cover.png',
  description='The fifth game in the series, Skyrim takes us on a journey through the coldest region of Cyrodiil. Once again player can traverse the open world RPG armed with various medieval weapons and magic, to become a hero of Nordic legends –Dovahkiin, the Dragonborn. After mandatory character creation players will have to escape not only imprisonment but a fire-breathing dragon. Something Skyrim hasn’t seen in centuries. After Oblivion, the magic system was reworked, in order to show players more aggressive and direct combat. As a Dragonborn, your character will be able to use the powerful magic of dragon shouts, powered, upgraded and researched with the souls of the dragons that will be randomly encountered by players, while traveling. Hundreds of sidequests will invite players to discover every part of the newly introduced land. Aside from already filled with guilds, Daedra and steampunk Dwemer ruins, Skyrim has additional DLC content that not only brings Solstheim island and vampire conclave but gives players the ability to build their own homes, instead of buying pre-made ones.')
  game32 = Game(category_id=5, title='Fall Out 4', 
  img='https://upload.wikimedia.org/wikipedia/en/7/70/Fallout_4_cover_art.jpg',
  description='The fourth game in the post-apocalyptic action RPG series from Bethesda studious brings players back to the retro-future. After customizing the facial features of the character, players will be admitted to the Vault 111 with their family, and tricked into entering the cryogenic capsule. After the rude awakening after the unknown amount of time has passed, the child is separated from the parents and the loving partner is killed in front of them – the main quest is settled. Now there’s only the giant open world to explore. Fallout 4 introduces the mechanics of settlement building, where players can build their own little town. Gathering material for crafting and building brings more “survival” elements into the old formula. Within their own settlements, players will be able to build all needed utilities, from storage spaces to power armor stations. Visual upgrade from the previous game brings life to what used to be brown wastelands, now filled with details and color.')
  game33 = Game(category_id=5, title='Horizon Zero Dawn', 
  img='https://upload.wikimedia.org/wikipedia/en/9/93/Horizon_Zero_Dawn.jpg',
  description="Horizon Zero Dawn is an experiment. A very impressive experiment that actually succeeded. Having a very curious mix of cyberpunk and prehistorical styles and esthetic, the game provides us with quite a unique experience. We need to arm ourselves with arrows and a bow, with a spear or any other prehistorical-ish weapon in order to defeat out enemies - dinosaur-mechanisms that are spread around the world. If that wasn't enough, Aloy our main protagonist can control an AI named GAIA. What we're having here is an exciting connection with 'very old times' and 'near future', even though the game is set up in the 31st century. Being an outcast with her father Rost, Aloy must restore her position in the tribe and save the world by stopping the Eclipse, a cult that wants to rule the world. Join her on that journey, exploring the world and people that live in such hard surroundings.")
  game34 = Game(category_id=5, title='The Legend of Zelda: Breath of the Wild', 
  img='https://upload.wikimedia.org/wikipedia/en/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg',
  description='The Legend of Zelda: Breath of the Wild is an adventure game developed by Nintendo. It is the nineteenth installment in the series. After awakening from a hundred year sleep, memoryless Link hears a mysterious female voice that guides him to a destroyed kingdom of Hyrule. He finds a Wiseman who says that a ruthless creature, Calamity Ganon, was imprisoned for 100 years. Even though the creature is trapped, it is still gaining power. Link sets out to kill Ganon before he frees himself and destroys the world. In contrast to the previous titles in the series, Breath of the Wild the player to explore a vast open world. At the beginning of the game, a small tutorial is given to the players and they are free to travel the world at the pace they see fit. Link can climb almost every surface in the world, cook food to restore health. Fast travel to certain places in the world is also available for the players. The world is highly interactive thanks to the chemistry engine.')
  game35 = Game(category_id=5, title='Ark: Survival Evolved', 
  img='https://upload.wikimedia.org/wikipedia/en/2/2b/ArkSurvivalEvolved.png',
  description="As a man or woman stranded naked, freezing and starving on the shores of a mysterious island called ARK, you must hunt, harvest resources, craft items, grow crops, research technologies, and build shelters to withstand the elements. Use your cunning and resources to kill or tame & breed the leviathan dinosaurs and other primeval creatures roaming the land, and team up with or prey on hundreds of other players to survive, dominate... and escape! We want to see what you create!")
  game36 = Game(category_id=5, title="World of Warcraft: Shadowlands", 
  img='https://upload.wikimedia.org/wikipedia/en/a/af/World_of_Warcraft_Shadowlands.jpg',
  description='What lies beyond the world you know? The Shadowlands, resting place for every mortal soul—virtuous or vile—that has ever lived. Pre-purchase the next World of Warcraft expansion now and be ready to discover what awaits in this world between worlds.')
  game37 = Game(category_id=6, title="Tom Clancy's Rainbow Six Siege", 
  img='https://upload.wikimedia.org/wikipedia/en/4/47/Tom_Clancy%27s_Rainbow_Six_Siege_cover_art.jpg',
  description='The gameplay of the game is based on intense strategic battles between the Navigator and the defenders in a limited space. Locations in the game consist of a multi-level object (for example, a multi-storey building), inside which there are defenders, and the area around it, where the attackers begin. Destruction is at the head of the game mechanics. The surrounding objects are created with maximum realism, the degree of damage depends on the calibre of the bullets used by the players or on the total power of the laid explosives. Walls can be destroyed, creating new firing positions and shelters. Optimal use of the potential of destruction often becomes a guarantee of victory. Defenders can limit the ability of attackers to destroy, using kits to strengthen the walls and the device of some operatives. The primary game mode - multiplayer, normal or rating. During the game in the last mode, the player is assigned a certain rank, and parameters such as the ratio of kills/deaths and wins/losses are recorded in his profile displayed in the game.')
  game38 = Game(category_id=6, title="Tom Clancy's Ghost Recon Breakpoint", 
  img='https://upload.wikimedia.org/wikipedia/en/b/ba/Cover_Art_of_Tom_Clancy%27s_Ghost_Recon_Breakpoint.png',
  description='Tom Clancy’s Ghost® Recon Breakpoint is a military shooter set in a diverse, hostile, and mysterious open world that you can play entirely solo or in four-player co-op. Injured, without support, and hunted down by ex-Ghosts, you must fight to survive while lost in Auroa. Choose the right alliances and decide how to take down your toughest enemy.')
  game39 = Game(category_id=6, title='Borderlands 3', 
  img='https://upload.wikimedia.org/wikipedia/en/2/21/Borderlands_3_cover_art.jpg',
  description='The original shooter-looter returns, packing bazillions of guns and a mayhem-fueled adventure! Blast through new worlds and enemies as one of four new Vault Hunters. Play solo or with friends to take on insane enemies, score loads of loot and save your home from the most ruthless cult leaders in the galaxy.')
  game40 = Game(category_id=6, title="Tom Clancy's The Division 2", 
  img='https://upload.wikimedia.org/wikipedia/en/a/af/The_Division_2_art.jpg',
  description="Tom Clancy's The Division 2 is the sequel to the 2016 Tom Clancy's The Division. The game is inspired by the Tom Clancy political thriller books. The game is set in the ruins of Washington D.C. in the near future, some seven months after the events of the original game. The smallpox epidemic devastated much of the United States, leaving it with multiple contamination zones. A civil war breaks out among the factions of survivors as the gangs of raiders terrorize the capital. The main characters are the elite members of the Strategic Homeland Division. Their task is to bring law and order back to Washington.")
  game41 = Game(category_id=6, title='Far Cry 5', 
  img='https://upload.wikimedia.org/wikipedia/en/0/03/Far_Cry_5_boxshot.jpg',
  description='Far Cry 5 is an open-world adventure first-person shooter developed by Ubisoft Montreal. It is the fifth main installment in the series. Welcome to Hope County, Montana, where a violent religious doomsday cult appeared. You play as a junior deputy sheriff who gets trapped in the Hope County as all the ways out the county are now patrolled with cultists and all external communication is cut off. It is your job to free the county of cultists. For the first time in the series, the game features a character creation screen. A wide range of weaponry which varies from pistols to grenade launchers is available to the player. Various vehicles are also at your exposal: cars, planes, helicopters, and so on. The game puts a strong emphasis on building the resistance to the cultists. Players have to recruit the locals in order to have more fighters and gain reputation.')
  game42 = Game(category_id=6, title='Call of Duty: Black Ops', 
  img='https://upload.wikimedia.org/wikipedia/en/0/02/CoD_Black_Ops_cover.png',
  description='Call of Duty: Black Ops is a first-person shooter, a seventh installment in the series altogether and a sequel to Call of Duty: World at War. The game takes place during the Cold War and shows different historical periods of it. The main character is a CIA agent, set out on different classified missions and tasked with eliminating enemies if needed. The story in the game is complicated, featuring characters from the previous games, and historical figures like JFK and Fidel Castro. Despite its emphasis on the scenario and real-world plausibility, Black Ops doesn’t lack in gameplay terms, as the combat system is, as established in series, extensive and realistic. The graphics are made for the player’s highest level of entertainment, with massive special effects and excellent quality of every detail. Call of Duty: Black Ops features a trademark multiplayer system, with different game modes, competitive play, and cooperative maps. The players can earn ranks for their performance, unlock new customizable weapons and different perks for use in the upcoming battles.')
  game43 = Game(category_id=7, title="FIFA 18", 
  img='https://upload.wikimedia.org/wikipedia/en/d/d4/FIFA18cover.png',
  description='FIFA 18 is the 25th instalment in the FIFA series and this one has Real Madrid player Cristiano Ronaldo on the cover of regular game edition. Ronaldo Nazario appears on the Icon edition of the game. FIFA 18 is the second game in FIFA series that uses Frostbite 3 engine yet some versions of FIFA 18 uses different game engine. Versions for PlayStation 4, Microsoft Windows and Xbox One include a single-player story driven mode called The Journey which is the continuation of the mod The Journey: Hunter Returns from the FIFA 17. Version for PlayStation 3 and Xbox 360 called FIFA 18: Legacy Edition do not include any new gameplay features yet it has updated kits and squads. FIFA 18 features 52 licensed stadiums from 12 countries, plus 30 generic fields. FIFA 18 has a new version of Ultimate Team Icons which includes legends like Diego Maradona, Pele, Ronaldo, Lev Yashin, Thierry Henry and other well-known players retired like Ronaldinho and Roberto Carlos.')
  game44 = Game(category_id=7, title="NBA 2K16", 
  img='https://upload.wikimedia.org/wikipedia/en/e/e0/NBA_2K16_cover_art.jpg',
  description='MyCAREER - A SPIKE LEE JOINTOur most intense first-person narrative to date, written and directed by Spike Lee. For the first time, manage your off days and earn bonus content through connections, endorsements and a live practice environment. 2K Pro-AmA groundbreaking new mode featuring fully customizable teams and 5v5 tournaments livestreamed on NBA 2KTV. Join forces with friends to create the perfect squad all the way down to custom logos, uniforms & arenas, or walk on and join any open game. ENHANCED GAMEPLAYA new motion engine generates smarter, hyper-realistic movement plus new ball & rim physics and player collisions, leading to a more intense and authentic on-court experience. PLAY NOW ONLINEThis year, online head-to-head games matter. For the first time, your online head-to-head record will determine whether or not you advance to higher levels. As you level up, you’ll unlock some of the greatest teams from NBA history to use in your games. FEATURED DJsDJ Khaled, DJ Mustard and DJ Premier produce our biggest soundtrack to date, featuring 50 dynamic tracks across 5 playlists and exclusive cuts from each DJ.')
  game45 = Game(category_id=7, title="NBA 2K20", 
  img='https://upload.wikimedia.org/wikipedia/en/e/e9/NBA_2K20_cover.png',
  description='NBA 2K has evolved into much more than a basketball simulation. 2K continues to redefine what’s possible in sports gaming with NBA 2K20, featuring best in class graphics & gameplay, ground breaking game modes, and unparalleled player control and customization. Plus, with its immersive open-world Neighborhood, NBA 2K20 is a platform for gamers and ballers to come together and create what’s next in basketball culture. Remote Play requires PS Vita system and sufficiently robust Wi-Fi connection.')
  game46 = Game(category_id=7, title="Steep", 
  img='https://upload.wikimedia.org/wikipedia/en/0/0b/Steep_cover_art.jpg',
  description='Ride a massive open world across the Alps, where the powder is always fresh and the run never ends. Defy and master the mountain alone or with friends on skis, wingsuits, snowboards and paragliders. Record and share your best stunts.')
  game47 = Game(category_id=7, title="EA Sports UFC 3", 
  img='https://upload.wikimedia.org/wikipedia/en/f/fc/EA_Sports_UFC_3_Official_Boxart.jpg',
  description='EA SPORTS™ UFC® 3 revolutionizes fighting movement with Real Player Motion Tech, delivering the most authentic athletic motion and visuals in sports gaming. In the new G.O.A.T. Career Mode, your choices outside the Octagon now matter as much as your performance inside the Octagon as you hype fights, create heated rivalries and more on the road to becoming the Greatest of All Time.')
  game48 = Game(category_id=7, title="Golf With Your Friends", 
  img='https://upload.wikimedia.org/wikipedia/en/2/21/GWF_header.jpg',
  description='Golf With Your Friends is an entertaining, challenging, multiplayer mini golf game for up to 12 players. The game currently has 6 levels containing 18 holes each. The controls are simple and the game is designed for the user to be able to host or join a game within a few seconds. The game will be hosted on our servers where the user has the ability to add a password if so required or leave it open to the public.Key Features 6 Vibrant challenging levels containing 18 holes each, 108 holes in total.')
  game49 = Game(category_id=8, title="Sid Meier's Civilization V", 
  img='https://upload.wikimedia.org/wikipedia/en/5/5c/CIVILIZATION-V-FRONT-OF-BOX.jpg',
  description='Real-time strategy genre has always been about domination over your opponent, and Civilization in general expanded on the concept. Civilization 5 allows players to pick one of the 43 civilizations available in, including DLCs and the expansions. After that players in single player or multiplayer games will place their first cities, which will act as capital, and begin the race. In order to win, players will have to meet one of the following conditions: - defeating every other existing nation through combat to get Domination Victory; - building and launching a spaceship to get Science victory; - completing the Utopia project by filling out 5 trees of social policies, to get Social Victory; - winning a vote after establishing the United Nations, to get the Diplomatic victory; - getting the highest score at the end of the time period, if no other win condition was reached, to get Time Victory. Every civilization is represented by one of the most influential historical figures and voiced in the language of that nation. Easy to pick up game mechanics of research, foraging, and building, allow the player to immerse themselves into the game atmosphere of continuous development.')
  game50 = Game(category_id=8, title="XCOM: Enemy Unknown", 
  img='https://upload.wikimedia.org/wikipedia/en/f/fd/XCOM_Enemy_Unknown_Game_Cover.jpg',
  description='Any alien invasion meets resistance in some form, so in this reboot of the series, players will take the mantle of the XCOM commander, and control the elite scientists and soldiers, in order to stop the threat. After successfully neutralizing scout ships, securing the crash site and retrieving civilians, XCOM personnel, and alien corpses, it’s clear that all of them are genetically and cybernetically altered, which starts the beginning of the arms race with the invaders. During the missions X-COM: Enemy Unknown is a turn-based tactical game, while in the downtime players will direct the organization, form units, oversee the research, expand the base of operations and manage resources. Complex combat consists of units taking turns to perform their actions with a top-down view of the battlefield. XCOM soldiers and aliens can take cover during battles, and miss their shots and attacks if anything affects their accuracy. Over the course of the game, players will be able to gain access to new technology while encountering new varied enemy types.')
  game51 = Game(category_id=8, title="Brutal Legend", 
  img='https://upload.wikimedia.org/wikipedia/en/8/83/BrutalLegendCover.jpg',
  description='Heavy Metal is a way of life and a world in itself, but Eddie Riggs found the real one, after the accident during a concert left him crushed by the scenery and making the involuntary blood sacrifice to the Ormagöden. The action adventure game with the real-time strategy elements in the open world introduced a star voice cast, compiled by musicians that became prototypes for some of the characters players will encounter during the game. Aside from the main story, players will be able to encounter dozens of side missions that may vary from the defense battles to a race. When using his V-guitar named Clementine, Eddie can cast spells, called Solos, by a simple rhythm game, reminiscent of Guitar Hero. Some story missions are so-called Battles of the Bands, where players will fight the armies in a real-time strategy fashion, and winning by outperforming the enemy band and destroying the stage.')
  game52 = Game(category_id=8, title="Cities: Skylines", 
  img='https://upload.wikimedia.org/wikipedia/en/5/58/Cities_Skylines_cover_art.jpg',
  description='Cities: Skylines is a traditional city-building game, which allows players to experience urban planning in all aspects including zoning, road placement, transportation, taxation, and improvement of welfare. Therefore, within the game players are able to assume roles of city’s principal architect and mayor. The history of the city, in control of the player, begins with the 2-by-2 kilometers plot of land and a sum of money to start with. Players have to zone the city, build roads, explore the surroundings, provide infrastructure and jobs to attract new citizens. Once the newcomers settle down, the immediate reaction is expected to establish public services and to set proper taxes. Progressing within the game and developing the city will unlock new upgrades of the urban environment and lead to the territorial expansion. The gameplay also requires the control of several city’s parameter scales like budget, health, employment, and pollution. The game also features a creative sandbox mode, where the architect’s imagination is not restricted in any way.')
  game53 = Game(category_id=8, title='Out of Space', 
  img='https://upload.wikimedia.org/wikipedia/en/3/38/Out_of_Space_Game.png',
  description='Out of Space is a cooperative multiplayer game about trying to live together in space. To live with your folks, or your boyfriend or your best friends is not an easy task. Who is going to take the trash out, do the dishes, or even walk with the dog? Oh... our mundanes things that makes us humans! -- But in outer space, it is not just a matter of making your home feel cozy, but actually, avoid getting killed in the process.')
 
  

  db.session.add(game1)
  db.session.add(game2)
  db.session.add(game3)
  db.session.add(game4)
  db.session.add(game5)
  db.session.add(game6)
  db.session.add(game7)
  db.session.add(game8)
  db.session.add(game9)
  db.session.add(game10)
  db.session.add(game11)
  db.session.add(game12)
  db.session.add(game13)
  db.session.add(game14)
  db.session.add(game15)
  db.session.add(game16)
  db.session.add(game17)
  db.session.add(game18)
  db.session.add(game19)
  db.session.add(game20)
  db.session.add(game21)
  db.session.add(game22)
  db.session.add(game23)
  db.session.add(game24)
  db.session.add(game25)
  db.session.add(game26)
  db.session.add(game27)
  db.session.add(game28)
  db.session.add(game29)
  db.session.add(game30)
  db.session.add(game31)
  db.session.add(game32)
  db.session.add(game33)
  db.session.add(game34)
  db.session.add(game35)
  db.session.add(game36)
  db.session.add(game37)
  db.session.add(game38)
  db.session.add(game39)
  db.session.add(game40)
  db.session.add(game41)
  db.session.add(game42)
  db.session.add(game43)
  db.session.add(game44)
  db.session.add(game45)
  db.session.add(game46)
  db.session.add(game47)
  db.session.add(game48)
  db.session.add(game49)
  db.session.add(game50)
  db.session.add(game51)
  db.session.add(game52)
  db.session.add(game53)


  db.session.commit()


def undo_games():
  db.session.execute('TRUNCATE games CASCASDE')
  db.session.commit()
